In [1]:
import pandas as pd
from pandas.tseries.frequencies import to_offset
import yfinance as yf
from datetime import datetime

today = datetime.today().strftime("%Y-%m-%d")

In [2]:
prices = yf.download("^NDX BTC-USD", start="2000-01-01", end=today)['Adj Close']
prices = prices.resample("W").last()
prices.index = prices.index + to_offset("-2d")
prices.dropna(inplace=True)
prices = prices[:-1] # delete the last (incomplete) week

prices.tail()

[*********************100%***********************]  2 of 2 completed

                 BTC-USD          ^NDX
Date
2022-07-29  23336.896484  12947.969727
2022-08-05  23175.890625  13207.690430
2022-08-12  24319.333984  13565.870117
2022-08-19  21534.121094  13242.900391
2022-08-26  19616.814453  12605.169922

In [3]:
returns = prices.pct_change()
returns['2yr_corr'] = returns['BTC-USD'].rolling(104).corr(returns['^NDX'])
returns['1yr_corr'] = returns['BTC-USD'].rolling(52).corr(returns['^NDX'])
returns['6mo_corr'] = returns['BTC-USD'].rolling(26).corr(returns['^NDX'])
returns['3mo_corr'] = returns['BTC-USD'].rolling(13).corr(returns['^NDX'])

returns.dropna(inplace=True)
returns

             BTC-USD      ^NDX  2yr_corr  1yr_corr  6mo_corr  3mo_corr
Date
2016-09-16  0.005200  0.029159  0.073055  0.154040  0.098982  0.436648
2016-09-23 -0.014836  0.008481  0.068541  0.149033  0.096450  0.105480
2016-09-30  0.016754  0.003456  0.063066  0.148942  0.124173 -0.134661
2016-10-07  0.009593 -0.002293  0.102597  0.146943  0.119725 -0.135273
2016-10-14  0.040339 -0.011520  0.102105  0.138498  0.110732 -0.341711
...              ...       ...       ...       ...       ...       ...
2022-07-29  0.032187  0.044488  0.408229  0.544234  0.623127  0.679387
2022-08-05 -0.006899  0.020059  0.404937  0.542710  0.628792  0.685075
2022-08-12  0.049338  0.027119  0.406337  0.551603  0.648472  0.679139
2022-08-19 -0.114527 -0.023808  0.417402  0.559749  0.650451  0.720927
2022-08-26 -0.089036 -0.048156  0.428986  0.571447  0.664211  0.808890

[311 rows x 6 columns]