In [1]:
import pandas as pd
import yfinance as yf

In [14]:
prices = yf.download("^GSPC ^NDX", start="1985-10-01", end="2022-05-03")['Adj Close']
prices.columns = ['SPX', 'NDX']
# ticker.index.name = 'date'
# ticker['dailyReturn'] = ticker['close'].pct_change()
# ticker['sd'] = ticker.dailyReturn.rolling(63).std() * math.sqrt(252)
prices

[*********************100%***********************]  2 of 2 completed

                    SPX           NDX
Date
1985-10-01   185.070007    112.139999
1985-10-02   184.059998    110.824997
1985-10-03   184.360001    110.870003
1985-10-04   183.220001    110.074997
1985-10-07   181.869995    108.199997
...                 ...           ...
2022-04-26  4175.200195  13009.709961
2022-04-27  4183.959961  13003.360352
2022-04-28  4287.500000  13456.059570
2022-04-29  4131.930176  12854.799805
2022-05-02  4155.379883  13075.849609

[9222 rows x 2 columns]

In [18]:
returns = prices.pct_change()
returns.dropna(inplace=True)
returns

                 SPX       NDX
Date
1985-10-02 -0.005457 -0.011726
1985-10-03  0.001630  0.000406
1985-10-04 -0.006184 -0.007171
1985-10-07 -0.007368 -0.017034
1985-10-08  0.000000 -0.009612
...              ...       ...
2022-04-26 -0.028146 -0.038683
2022-04-27  0.002098 -0.000488
2022-04-28  0.024747  0.034814
2022-04-29 -0.036285 -0.044683
2022-05-02  0.005675  0.017196

[9221 rows x 2 columns]

In [19]:
#resample daily data to calulate weekly returns
wkly_returns = pd.DataFrame(returns.resample("W").apply(lambda x: ((x + 1).cumprod() - 1).last("D")))
wkly_returns.head()

                 SPX       NDX
Date
1985-10-06 -0.009996 -0.018415
1985-10-13  0.005785  0.008858
1985-10-20  0.014977  0.029446
1985-10-27  0.002566 -0.003586
1985-11-03  0.021384  0.020762

In [25]:
counter = 0
def downWeeks(x):
    global counter
    if x >= 0:
        counter = 0
        return counter
    else:
        counter += 1
        return counter

In [26]:
def downMonths(x):
    index = ndxm.index.get_loc(x.name)
    if index == 0:
        return 0
    prev_x = ndxm.iloc[index-1]
    if x['monthlyReturn'] >= 0:
        return 0
    else:
        return downMonths(prev_x) + 1

In [28]:
wkly_returns['SPX down'] = wkly_returns['SPX'].apply(downWeeks)
wkly_returns['NDX down'] = wkly_returns['NDX'].apply(downWeeks)
wkly_returns

                 SPX       NDX  SPX down  NDX down
Date
1985-10-06 -0.009996 -0.018415         1         1
1985-10-13  0.005785  0.008858         0         0
1985-10-20  0.014977  0.029446         0         0
1985-10-27  0.002566 -0.003586         0         1
1985-11-03  0.021384  0.020762         0         0
...              ...       ...       ...       ...
2022-04-10 -0.012666 -0.035929         1         1
2022-04-17 -0.021320 -0.030295         2         2
2022-04-24 -0.027503 -0.038604         3         3
2022-05-01 -0.032738 -0.037589         4         4
2022-05-08  0.005675  0.017196         0         0

[1910 rows x 4 columns]

In [31]:
wkly_returns.loc[(wkly_returns['SPX down'] >=5) & (wkly_returns['NDX down'] >= 5),['DatSPX down', 'NDX down']]

KeyError: "['Date'] not in index"