In [18]:
import pandas as pd
from pandas.tseries.frequencies import to_offset
import yfinance as yf
from datetime import datetime

today = datetime.today().strftime("%Y-%m-%d")

In [36]:
prices = yf.download("^GSPC ^NDX ^DJI", start="1985-10-01", end=today)['Adj Close']
prices = prices.resample("W").last()
prices.index = prices.index + to_offset("-2d")
prices.dropna(inplace=True)
prices[:10]

[*********************100%***********************]  3 of 3 completed

                   ^DJI       ^GSPC        ^NDX
Date
1992-01-03  3201.500000  419.339996  334.825012
1992-01-10  3199.500000  415.100006  347.109985
1992-01-17  3265.000000  418.859985  349.730011
1992-01-24  3232.800049  415.480011  345.454987
1992-01-31  3223.399902  408.779999  338.315002
1992-02-07  3225.399902  411.089996  346.804993
1992-02-14  3246.000000  412.480011  346.695007
1992-02-21  3280.199951  411.429993  342.390015
1992-02-28  3267.699951  412.700012  345.880005
1992-03-06  3221.600098  404.440002  333.000000

In [25]:
returns = prices.pct_change()
returns.dropna(inplace=True)
returns

                ^DJI     ^GSPC      ^NDX
Date
1992-01-10 -0.000625 -0.010111  0.036691
1992-01-17  0.020472  0.009058  0.007548
1992-01-24 -0.009862 -0.008069 -0.012224
1992-01-31 -0.002908 -0.016126 -0.020668
1992-02-07  0.000620  0.005651  0.025095
...              ...       ...       ...
2022-04-22 -0.018572 -0.027503 -0.038604
2022-04-29 -0.024672 -0.032738 -0.037589
2022-05-06 -0.002360 -0.002079 -0.012545
2022-05-13 -0.021359 -0.024119 -0.024117
2022-05-20 -0.029305 -0.030592 -0.041314

[1585 rows x 3 columns]

In [26]:
counter = 0
def downWeeks(x):
    global counter
    
    if x >= 0:
        counter = 0
        return counter
    else:
        counter += 1
        return counter
streaks = pd.Dataframe()
streaks.loc[returns.index.min(),'SPX down weeks']
for i in range(0, len(returns):

In [34]:
streaks = pd.DataFrame()
firstDate = streaks.index.min()
streaks['SPX down weeks'] = returns['^GSPC'].apply(downWeeks, axis=1, minDate)
streaks['NDX down weeks'] = returns['^NDX'].apply(ownWeeks, axis=1, minDate)
streaks['DJIA down weeks'] = returns['^DJI'].apply(ownWeeks, axis=1, minDate)
streaks

            SPX down weeks  NDX down weeks  DJIA down weeks
Date
1992-01-10               9               0                8
1992-01-17               0               0                0
1992-01-24               1               1                1
1992-01-31               2               2                2
1992-02-07               0               0                0
...                    ...             ...              ...
2022-04-22               3               3                4
2022-04-29               4               4                5
2022-05-06               5               5                6
2022-05-13               6               6                7
2022-05-20               7               7                8

[1585 rows x 3 columns]

In [33]:
wkly_returns.loc[(streaks['SPX down weeks'] >=6) &
                 (streaks['NDX down weeks'] >= 6) &
                 (streaks['DJIA down weeks'] >= 6),['SPX down weeks', 'NDX down weeks','DJIA down weeks']]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).